name: Java CI with Docker and Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start containers
        run: docker compose -f "test.yml" up -d
      - name: Wait for containers to settle
        run: docker exec -i jaws bash -c "sleep 20"
      - name: Run integration test
        run: docker exec -i client sh -c "cd /app; gradle integrationTest"
      - name: Dump jaws logs
        if: always()
        run: docker logs jaws
      - name: Dump client logs
        if: always()
        run: docker logs client
      - name: Stop containers
        if: always()
        run: docker compose -f "test.yml" down
