name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'VERSION'
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start containers
        run: docker compose -f deps.yaml up -d
      - name: Wait for containers to settle
        run: docker exec -i kafka bash -c "sleep 20"
      - name: Run build and integration test
        run: ./gradlew integrationTest
      - name: Stop containers
        if: always()
        run: docker compose -f deps.yaml down
